Add unsupported SMT Array primitives.
GaloisInc/saw-core-sbv pull request #3
Opened 2020-05-18 22:28 UTC by andreistefanescu

Depends on GaloisInc/saw-core#54

2020-05-19 21:37 UTC, atomb commented on src/Verifier/SAW/Simulator/SBV.hs
> +  , Prims.bpArrayUpdate = error "bpArrayUpdate unimplemented for backend"
Like in the `saw-core` package, I think we should make sure these error messages would be meaningful to a user, and specify which backend we're talking about.

2020-05-19 23:07 UTC, brianhuffman commented on src/Verifier/SAW/Simulator/SBV.hs
> +  , Prims.bpArrayUpdate = error "bpArrayUpdate unimplemented for backend"
I know there are other calls to `error` and `undefined` in the same module, so this is not really any worse... but we should probably avoid using `error` if at all possible. I suppose using an array prim doesn't merit a `panic`, so we should probably throw some kind of `IO` exception instead.

At the very least, we should define some wrapper function around `error` to use for all these unimplemented primitives; then at least it will easier to go back later and fix them all at once.

2020-05-19 23:11 UTC, atomb commented on src/Verifier/SAW/Simulator/SBV.hs
> +  , Prims.bpArrayUpdate = error "bpArrayUpdate unimplemented for backend"
Yeah, I second @brianhuffman's comment.

2020-05-19 23:14 UTC, brianhuffman requested changes
I'm happy with everything except the calls to `error`.

2020-05-19 23:17 UTC, brianhuffman commented
In the longer term, instead of raising a run-time error for any use of the array primitives, we might try an approach similar to how the `RME` and `AIG` backends handle the `Integer` type: Neither backend can handle symbolic integers, but they do allow integer values as long as they are concrete. We might be able to do something similar for arrays in the sbv backend, where we can use them as long as the array indices are all concrete values, and only raise a run-time error if we come across a symbolic one.

2020-05-26 20:38 UTC, andreistefanescu commented on src/Verifier/SAW/Simulator/SBV.hs
> +  , Prims.bpArrayUpdate = error "bpArrayUpdate unimplemented for backend"
@brianhuffman take a look at https://github.com/GaloisInc/saw-core/pull/55

2020-06-05 21:34 UTC, brianhuffman approved these changes
As of f9dd550, this looks good.

2020-06-10 04:32 UTC, merged